
inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/console'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/sdr_client/deposit/process_spec.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    -  'sdr-client.gemspec'
  ExcludedMethods:
    - 'OptionParser.new'

Naming/FileName:
  Exclude:
    - 'lib/sdr-client.rb'