inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/console'
    - 'vendor/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    -  'sdr-client.gemspec'
  ExcludedMethods:
    - 'OptionParser.new'

Metrics/ClassLength:
  Exclude:
    - 'lib/sdr_client/deposit/request.rb'

Naming/FileName:
  Exclude:
    - 'lib/sdr-client.rb'
